# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QFrame,
    QHeaderView, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTableWidget, QTableWidgetItem,
    QTextBrowser, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1131, 735)
        font = QFont()
        font.setFamilies([u"Arial"])
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.scrcpy = QPushButton(self.centralwidget)
        self.scrcpy.setObjectName(u"scrcpy")
        self.scrcpy.setGeometry(QRect(400, 10, 71, 31))
        self.browse = QPushButton(self.centralwidget)
        self.browse.setObjectName(u"browse")
        self.browse.setGeometry(QRect(20, 10, 101, 31))
        self.listExported = QListWidget(self.centralwidget)
        self.listExported.setObjectName(u"listExported")
        self.listExported.setGeometry(QRect(20, 90, 471, 81))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 60, 141, 16))
        self.adbLaunch = QPushButton(self.centralwidget)
        self.adbLaunch.setObjectName(u"adbLaunch")
        self.adbLaunch.setGeometry(QRect(210, 370, 100, 31))
        self.addExtras = QPushButton(self.centralwidget)
        self.addExtras.setObjectName(u"addExtras")
        self.addExtras.setGeometry(QRect(20, 370, 61, 32))
        self.extrasTable = QTableWidget(self.centralwidget)
        if (self.extrasTable.columnCount() < 3):
            self.extrasTable.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.extrasTable.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.extrasTable.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.extrasTable.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        self.extrasTable.setObjectName(u"extrasTable")
        self.extrasTable.setGeometry(QRect(20, 410, 471, 171))
        self.extrasTable.setContextMenuPolicy(Qt.ContextMenuPolicy.ActionsContextMenu)
        self.extrasTable.setFrameShape(QFrame.Shape.Box)
        self.extrasTable.setFrameShadow(QFrame.Shadow.Raised)
        self.extrasTable.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.extrasTable.setEditTriggers(QAbstractItemView.EditTrigger.AllEditTriggers)
        self.extrasTable.setAlternatingRowColors(True)
        self.extrasTable.setRowCount(0)
        self.extrasTable.setColumnCount(3)
        self.extrasTable.horizontalHeader().setCascadingSectionResizes(False)
        self.extrasTable.horizontalHeader().setStretchLastSection(True)
        self.extrasTable.verticalHeader().setVisible(True)
        self.extrasTable.verticalHeader().setCascadingSectionResizes(False)
        self.removeExtras = QPushButton(self.centralwidget)
        self.removeExtras.setObjectName(u"removeExtras")
        self.removeExtras.setGeometry(QRect(100, 370, 61, 32))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 230, 141, 16))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(7, 210, 491, 20))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(490, 10, 20, 651))
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 40, 491, 20))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.outputText = QTextBrowser(self.centralwidget)
        self.outputText.setObjectName(u"outputText")
        self.outputText.setGeometry(QRect(20, 590, 471, 71))
        self.actionLine = QLineEdit(self.centralwidget)
        self.actionLine.setObjectName(u"actionLine")
        self.actionLine.setGeometry(QRect(90, 260, 391, 31))
        self.dataLine = QLineEdit(self.centralwidget)
        self.dataLine.setObjectName(u"dataLine")
        self.dataLine.setGeometry(QRect(90, 300, 391, 31))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 260, 51, 31))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 300, 51, 31))
        self.activityText = QLineEdit(self.centralwidget)
        self.activityText.setObjectName(u"activityText")
        self.activityText.setGeometry(QRect(20, 180, 471, 31))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(520, 15, 151, 21))
        self.apkCodeGenerate = QPushButton(self.centralwidget)
        self.apkCodeGenerate.setObjectName(u"apkCodeGenerate")
        self.apkCodeGenerate.setGeometry(QRect(360, 370, 81, 31))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 350, 141, 21))
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(10, 330, 491, 20))
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(200, 340, 3, 61))
        self.line_5.setFrameShape(QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(210, 350, 81, 21))
        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(340, 340, 20, 61))
        self.line_6.setFrameShape(QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(360, 350, 71, 20))
        self.line_7 = QFrame(self.centralwidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(170, 396, 331, 16))
        self.line_7.setFrameShape(QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.javaCode = QTextEdit(self.centralwidget)
        self.javaCode.setObjectName(u"javaCode")
        self.javaCode.setGeometry(QRect(520, 40, 581, 621))
        font1 = QFont()
        font1.setFamilies([u"Menlo"])
        font1.setPointSize(13)
        self.javaCode.setFont(font1)
        self.javaCode.setInputMethodHints(Qt.InputMethodHint.ImhMultiLine|Qt.InputMethodHint.ImhNoAutoUppercase|Qt.InputMethodHint.ImhNoEditMenu|Qt.InputMethodHint.ImhNoPredictiveText)
        self.javaCode.setFrameShape(QFrame.Shape.WinPanel)
        self.javaCode.setFrameShadow(QFrame.Shadow.Sunken)
        self.javaCode.setLineWrapMode(QTextEdit.LineWrapMode.WidgetWidth)
        self.javaCode.setReadOnly(True)
        self.javaCode.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
        self.jadx = QPushButton(self.centralwidget)
        self.jadx.setObjectName(u"jadx")
        self.jadx.setGeometry(QRect(310, 10, 71, 31))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1131, 33))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.scrcpy.setText(QCoreApplication.translate("MainWindow", u"Scrcpy", None))
        self.browse.setText(QCoreApplication.translate("MainWindow", u"Browse APK", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Exported Activities :", None))
        self.adbLaunch.setText(QCoreApplication.translate("MainWindow", u"Launch", None))
#if QT_CONFIG(tooltip)
        self.addExtras.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Add Extras</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.addExtras.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        ___qtablewidgetitem = self.extrasTable.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Type", None));
        ___qtablewidgetitem1 = self.extrasTable.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Key", None));
        ___qtablewidgetitem2 = self.extrasTable.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Value", None));
        self.removeExtras.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Configure Intent :", None))
#if QT_CONFIG(tooltip)
        self.actionLine.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>E.g. <span style=\" font-family:'Helvetica'; font-size:12px;\">android.intent.action.VIEW</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.dataLine.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Value of -d</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Action :", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Data :", None))
#if QT_CONFIG(tooltip)
        self.activityText.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>E.g. <span style=\" font-family:'Helvetica'; font-size:12px;\">android.intent.action.VIEW</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Java Code :", None))
        self.apkCodeGenerate.setText(QCoreApplication.translate("MainWindow", u"Generate", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Configure Extras :", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Using ADB :", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Using APK :", None))
        self.javaCode.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Menlo'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.jadx.setText(QCoreApplication.translate("MainWindow", u"Jadx-gui", None))
    # retranslateUi

